apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hashi-audit-export
  namespace: hashi-enterprise
  labels:
    app.kubernetes.io/name: hashi
    app.kubernetes.io/component: audit-export
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: enterprise-secret-store
    kind: ClusterSecretStore
  target:
    name: hashi-audit-export
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: hashi
          app.kubernetes.io/component: audit-export
  data:
    - secretKey: HASHI_AUDIT_EXPORT_ENDPOINT
      remoteRef:
        key: hashi/enterprise/audit-export
        property: endpoint
    - secretKey: HASHI_AUDIT_EXPORT_HEADER
      remoteRef:
        key: hashi/enterprise/audit-export
        property: authorization_header
