apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: enterprise-secret-store
  labels:
    app.kubernetes.io/name: hashi
    app.kubernetes.io/component: audit-export
spec:
  provider:
    gcpsm:
      projectID: your-gcp-project-id
      auth:
        workloadIdentity:
          clusterLocation: australia-southeast1
          clusterName: your-gke-cluster
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
