apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: enterprise-secret-store
  labels:
    app.kubernetes.io/name: hashi
    app.kubernetes.io/component: audit-export
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: https://your-key-vault.vault.azure.net/
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets
