apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: enterprise-secret-store
  labels:
    app.kubernetes.io/name: hashi
    app.kubernetes.io/component: audit-export
spec:
  provider:
    vault:
      server: https://vault.example.com
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: hashi-enterprise
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
