apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hashi-enterprise.fullname" . }}-config
  labels:
    {{- include "hashi-enterprise.labels" . | nindent 4 }}
data:
  HASHI_DEPLOYMENT_PROFILE: {{ .Values.enterprise.deploymentProfile | quote }}
  HASHI_INSTANCE_ID: {{ .Values.enterprise.instanceId | quote }}
  HASHI_ORGANIZATION_ID: {{ .Values.enterprise.organizationId | quote }}
  HASHI_BRIDGE_HOME: {{ .Values.enterprise.bridgeHome | quote }}
  HASHI_WORKBENCH_PORT: {{ .Values.enterprise.workbenchPort | quote }}
