{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "hashi-enterprise.fullname" . }}
  labels:
    {{- include "hashi-enterprise.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hashi-enterprise.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.ingressNamespaceSelector | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
  egress:
    {{- if .Values.networkPolicy.egress.allowDns }}
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- end }}
    {{- if .Values.networkPolicy.egress.allowAll }}
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
    {{- end }}
{{- end }}
