apiVersion: v1
kind: Service
metadata:
  name: {{ include "hashi-enterprise.fullname" . }}
  labels:
    {{- include "hashi-enterprise.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: workbench
      port: {{ .Values.service.port }}
      targetPort: workbench
  selector:
    app.kubernetes.io/name: {{ include "hashi-enterprise.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
