apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hashi-enterprise-lease
  namespace: hashi-enterprise
  labels:
    app.kubernetes.io/name: hashi
    app.kubernetes.io/component: enterprise
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hashi-enterprise-lease
  namespace: hashi-enterprise
  labels:
    app.kubernetes.io/name: hashi
    app.kubernetes.io/component: enterprise
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hashi-enterprise-lease
