apiVersion: v1
kind: Service
metadata:
  name: hashi-enterprise-workbench
  namespace: hashi-enterprise
  labels:
    app.kubernetes.io/name: hashi
    app.kubernetes.io/component: enterprise
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: hashi
    app.kubernetes.io/component: enterprise
  ports:
    - name: workbench
      port: 18800
      targetPort: workbench
